# Generated by Django 5.0.4 on 2024-05-01 08:13

import django.db.models.deletion
import domain.enum.category_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('text', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', domain.enum.category_field.EnumField(enum=domain.enum.category_field.CategoryType, max_length=104)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='domain.statement')),
            ],
        ),
    ]
